### ISSUE TITLE
Sample code for WebAPI

### ISSUE THREAD

**Issue by FRRago** [rlvandaveer/heliar-composition#11]
Hi,

This is not really an issue with the package, but I'm trying to understand how to use it on a simple WebAPI application.
I suppose this package would enable me to create a new object instance implementing IDependencyResolver, and set it on config.DependencyResolver, but I didnt got how to do it.

Could you help provigin a simple sample code?
Thanks

**Comment by rlvandaveer** [comment]
Hello. I'm sorry for the late response. I haven't used or maintained this for a long time. There are much more robust DI frameworks now-a-days.
